---
- name: "Validate configuration"
  assert:
    that:
      - FUNKWHALE_VERSION is defined
      - FUNKWHALE_PROTOCOL is defined
      - FUNKWHALE_HOSTNAME is defined
      - # Generate one using `openssl rand -base64 45`, for example
      - funkwhale_secret is defined
      - funkwhale_db is defined
      - funkwhale_db_user is defined
      - funkwhale_db_password is defined
      - FUNKWHALE_DB_REPO is defined
      - FUNKWHALE_DB_VER is defined
      - FUNKWHALE_CONFIG_PATH is defined
      - FUNKWHALE_FRONTEND_PATH is defined
      - FUNKWHALE_MEDIA_ROOT is defined
      - FUNKWHALE_STATIC_ROOT is defined
      - FUNKWHALE_MUSIC_DIRECTORY_SERVE_PATH is defined
      - FUNKWHALE_MUSIC_DIRECTORY_PATH is defined
      - FUNKWHALE_NGINX_MAX_BODY_SIZE is defined
      - FUNKWHALE_API_IP is defined
      - FUNKWHALE_API_PORT is defined

- name: "install pre packages"
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - git
    - unzip
    - curl
    - python3
    - python3-pip

- name: "Set OS distribution dependent variables"
  include_vars: "{{ ansible_facts['distribution'] }}.yml"

- name: "Install packages"
  include_tasks: "install_{{ ansible_facts['distribution'] }}.yml"


- name: "check out {{ FUNKWHALE_VERSION }}"
  git:
    repo: 'https://dev.funkwhale.audio/funkwhale/funkwhale'
    dest: /srv/funkwhale
    version: 1.2.10
  register: cloning_funkwhale

- debug:
    var: cloning_funkwhale

- name: "Download a front"
  ansible.builtin.get_url:
    url: "https://dev.funkwhale.audio/funkwhale/funkwhale/-/jobs/artifacts/{{ FUNKWHALE_VERSION }}/download?job=build_front"
    dest: "/srv/funkwhale/front.zip"

- name: Unarchive a front
  ansible.builtin.unarchive:
    src: /srv/funkwhale/front.zip
    dest: /srv/funkwhale
    remote_src: yes

- name: "Add the user"
  user:
    name: funkwhale
    shell: /usr/bin/nologin
    home: /srv/funkwhale

- name: "Install wheel to virtualenv"
  pip:
    name: wheel
    virtualenv: /srv/funkwhale/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv
  when: cloning_funkwhale.changed

- name: "Upgrade pip to the last version"
  pip:
    name: pip
    virtualenv: /srv/funkwhale/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv
    extra_args: --upgrade pip
  register: venv_upgrade
  when: cloning_funkwhale.changed

- name: "Install requirements"
  pip:
    requirements: /srv/funkwhale/api/requirements.txt
    virtualenv: /srv/funkwhale/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv
  when: venv_upgrade.changed and cloning_funkwhale.changed
  register: venv_req

- name: "Install pyopenssl to virtualenv"
  pip:
    name: pyopenssl
    virtualenv: /srv/funkwhale/virtualenv
    virtualenv_command: /usr/bin/python3 -m venv
    extra_args: --upgrade pip
  when: cloning_funkwhale.changed and venv_upgrade.changed  and venv_req.changed


# TODO postgres and redis must be on the same host
- name: "Configure beat systemd service"
  template:
    src: funkwhale-beat.service.j2
    dest: "/etc/systemd/system/funkwhale-beat.service"


- name: "Configure server systemd service"
  template:
    src: funkwhale-server.service.j2
    dest: "/etc/systemd/system/funkwhale-server.service"


- name: "Configure worker systemd service"
  template:
    src: funkwhale-worker.service.j2
    dest: "/etc/systemd/system/funkwhale-worker.service"


- name: "Configure systemd target"
  template:
    src: funkwhale.target.j2
    dest: "/etc/systemd/system/funkwhale.target"

- name: "Create config directories"
  file:
    path: "{{ item }}"
    owner: funkwhale
    group: root
    state: directory
  loop:
    - "{{ FUNKWHALE_CONFIG_PATH }}"
    - "{{ FUNKWHALE_MEDIA_ROOT }}"
    - "{{ FUNKWHALE_STATIC_ROOT }}"
    - "{{ FUNKWHALE_MUSIC_DIRECTORY_SERVE_PATH }}"
    - "{{ FUNKWHALE_MUSIC_DIRECTORY_PATH }}"

- name: "Configure service"
  template:
    src: env.j2
    dest: "/srv/funkwhale/config/.env"
    owner: funkwhale
    group: root
    mode: 0600

- name: "Run an initial migration"
  django_manage:
    command: migrate
    app_path: "/srv/funkwhale/api"
    pythonpath: "/usr/bin/python3"
    virtualenv: "/srv/funkwhale/virtualenv"
  notify:
    - nginx systemd

- name: "Systemd units are enabled"
  ansible.builtin.systemd:
    name: '{{ item }}'
    daemon_reload: true
    enabled: true
    state: started
  loop:
    - funkwhale.target
    - redis.service
    - nginx.service
  register: result_systemd

# the must for unexisted dns hostname. but hosts is untouchable on docker
- name: "hostname to hosts"
  block:
    - name: "try to insert"
      lineinfile:
        path: /etc/hosts
        line: "{{ FUNKWHALE_API_IP }} {{ FUNKWHALE_HOSTNAME }}"
      become: yes
  rescue:
    - debug:
        msg: "Cannot modify hosts. Docker? You should add {{ FUNKWHALE_API_IP }} {{ FUNKWHALE_HOSTNAME }} to /etc/hosts manually"

- name: "Check for proper.front.response"
  uri:
    url: "http://{{ FUNKWHALE_HOSTNAME }}/"
    return_content: true
    method: GET
    status_code: 200
  register: result_front
  until: '"Funkwhale" in result_front.content'
  retries: 3
  delay: 1
  tags: molecule-notest

- debug:
    var: result_front
  tags: molecule-notest

- name: "Check result proper Front response"
  assert:
    that:
      - not result_front.changed
    fail_msg: "'Fail' on {{inventory_hostname}} {{ ansible_default_ipv4.address }}"
    success_msg: "'Success' on {{inventory_hostname}} {{ ansible_default_ipv4.address }}"
  tags: molecule-notest
